version: '3.8'

services:
  weather-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY:-}
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - weather-network

  # Optional: Redis for caching (can be enabled later)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - weather-network

networks:
  weather-network:
    driver: bridge